### ISSUE TITLE
Creating new podcast goes to 500 error page.

### ISSUE THREAD

**Issue by nostitos** [dennisreimann/btcpayserver-plugin-podserver#7] opened 2023-11-13 15:38 UTC
This page isn’t working ... is currently unable to handle this request.
HTTP ERROR 500

![image](https://github.com/dennisreimann/btcpayserver-plugin-podserver/assets/48504624/044a5c17-2019-4337-8908-2f358396cb44)

Entering any names here leads to 500 page

The podcast names then shows in the sidebar, 
Clicking it also goes to the same 500 page, 
Cannot remove the podcast afterward,

**Comment by dennisreimann** [comment] 2023-11-14 08:43
I cannot reproduce this. Can you tell me which versions (BTCPay and PodServer) you are running and post the logs from the BTCPay Server container?

```bash
docker logs generated_btcpayserver_1
```

**Comment by dennisreimann** [comment] 2023-11-16 06:32
Fixed with 65de55af887369a3d819f7d551d090b502df74fa, see #4.

**Closed by dennisreimann** 2023-11-16 06:32 UTC
